micronaut:
    application:
        name: pg-example
    server:
        cors:
            enabled: true
        port: 7777

postgres:
    reactive:
        client:
            port: 5432
            host: localhost
            database: deps
            user: deps
            password: timbub12
            maxSize: 5